version: 2

jobs:
  build:
    docker:
      # cloud functionsがv8までしかサポートしていないためv8にしておく
      - image: node:8.15.0-alpine
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: apk add --no-cache ca-certificates
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package.json" }}
            # Find the most recent cache used from any branch
            - v2-npm-deps-
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: clean dist dir
          command: npm run clean
      - run:
          name: build
          command: npm run predeploy
      - save_cache:
          key: v2-npm-deps-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: node:8.15.0-alpine
    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .
      - run:
          name: set environment variables
          command: npm run set-env
      - run:
          name: deploy to firebase
          command: npm run deploy:ci

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
