version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key:
            - v1-npm-deps-{{ checksum "package.json" }}
            # Find the most recent cache used from any branch
            - v1-npm-deps-
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: clean dist dir
          command: npm run clean
      - run:
          name: build
          command: npm run predeploy
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .
      - run:
          name: set environment variables
          command: npm run set-env
      - run:
          name: deploy to firebase
          command: npm run deploy:ci

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
